module.exports = [
  "Anthropology",
 	"Applied Mathematics",
 	"Applied Science",
 	"Arts Center",
 	"Arts and Design",
 	"Astronomy",
  "Bioinformatics and Structural Biology",
 	"Biomedical Engineering",
 	"Biomedical Engineering and Envionmenttal Sciences",
 	"Biotechnology",
  "Center for General Education",
 	"Center for Teacher Education",
 	"Chemical Engineering",
 	"Chemistry",
 	"Chinese Language and Literature",
 	"Chinese Literature",
 	"Communications Engineering",
 	"Computer Science",
  "Dual Master Program for Global Operation Management",
  "EMBA",
 	"EMBA/MBA",
 	"Economics",
 	"Education and Learning Technology",
 	"Educational Psychology and Counseling",
 	"Electrical Engineering",
 	"Electrical Engineering and Computer Science - Interdisciplinary Program",
 	"Electronics Engineering",
 	"Engineering - Interdisciplinary Program",
 	"Engineering and System Science",
 	"English Instruction",
 	"Environmental and Cultural Resources",
 	"Early Childhood Education",
  "Foreign Languages and Literature",
  "General Education",
 	"Graduate Human Resource and eLearning Technology",
 	"Graduate Mathematics and Science Education",
 	"Graduate Program in Science and Technology of Synchrotron Light Source",
 	"Graduated Program of Taiwan Studies for in-service Teachers",
  "History",
 	"Hsinchu Teachers College",
 	"Humanities and Social Sciences",
  "IMBA",
 	"Industrial Engineering and Engineering Management",
 	"Information Systems and Applications",
 	"Institute for Computational and Modeling Science",
 	"Interdisciplinary Program",
 	"Interdisciplinary Program of Electrical Engineering and Computer Science",
 	"Interdisciplinary Program of Engineering",
 	"Interdisciplinary Program of Humanities and Social Sciences",
 	"Interdisciplinary Program of Life Science",
 	"Interdisciplinary Program of Management",
 	"Interdisciplinary Program of Nuclear Science",
 	"Interdisciplinary Program of Sciences",
 	"International Graduate Program in inter-Asia Cultural",
 	"International Institute for Cultural Studies",
 	"International Intercollegiate MS Program",
 	"International Intercollegiate PhD Program",
  "Law for Science and Technology",
 	"Learning Science and Technology",
 	"Learning Sciences",
 	"Life Science",
 	"Life Science - Interdisciplinary Program",
 	"Linguistics",
  "MBA",
 	"Management - Interdisciplinary Program",
 	"Materials Science Engineering",
 	"Mathematics",
 	"Medical Science",
 	"Military Education Office",
 	"Molecular Medicine",
 	"Molecular and Cellular Biology",
 	"Music",
  "Nanoengineering and Microsystems",
 	"Nuclear Engineering and Science (NES)",
 	"Nuclear Science - Interdisciplinary Program",
  "Philosophy",
 	"Photonics Technologies",
 	"Physical Education",
 	"Physical Education Office",
 	"Physics",
 	"Power Mechanical Engineering",
  "Quantitative Finance",
  "Sciences - Interdisciplinary Program",
 	"Service Science",
 	"Sociology",
 	"Special Education",
 	"Statistics",
 	"Systems Neuroscience",
  "Taiwan Languages and Language Teaching",
 	"Taiwan Literature",
 	"Taiwan Studies",
 	"Teacher Education",
 	"Teaching Chinese as a Second/Foreign Language - Interdisciplinary Program",
 	"Technology Management",
 	"Tsing Hua College"
]
